services:
  - type: web
    name: amazon-price-tracker
    env: python
    plan: free
    buildCommand: pyenv install 3.11.9 && pyenv global 3.11.9 && pip install -r requirements.txt
    startCommand: gunicorn amazonPriceTracker.wsgi
